CREATE UNIQUE INDEX HCM.DEPT_ID_PK ON HCM.DEPARTMENTS (DEPARTMENT_ID ASC);

CREATE INDEX HCM.DEPT_LOCATION_IX ON HCM.DEPARTMENTS (LOCATION_ID ASC);

CREATE INDEX HCM.EMP_DEPARTMENT_IX ON HCM.EMPLOYEES (DEPARTMENT_ID ASC);

CREATE UNIQUE INDEX HCM.EMP_EMP_ID_PK ON HCM.EMPLOYEES (EMPLOYEE_ID ASC);

CREATE INDEX HCM.EMP_JOB_IX ON HCM.EMPLOYEES (JOB_ID ASC);

CREATE INDEX HCM.EMP_MANAGER_IX ON HCM.EMPLOYEES (MANAGER_ID ASC);

CREATE INDEX HCM.EMP_NAME_IX ON HCM.EMPLOYEES (LAST_NAME ASC, FIRST_NAME ASC);

CREATE UNIQUE INDEX HCM.JOB_ID_PK ON HCM.JOBS (JOB_ID ASC);

CREATE INDEX HCM.JHIST_DEPARTMENT_IX ON HCM.JOB_HISTORY (DEPARTMENT_ID ASC);

CREATE INDEX HCM.JHIST_EMPLOYEE_IX ON HCM.JOB_HISTORY (EMPLOYEE_ID ASC);

CREATE UNIQUE INDEX HCM.JHIST_EMP_ID_ST_DATE_PK ON HCM.JOB_HISTORY (EMPLOYEE_ID ASC, START_DATE ASC) ;

CREATE INDEX HCM.JHIST_JOB_IX ON HCM.JOB_HISTORY (JOB_ID ASC) ;

CREATE INDEX HCM.LOC_CITY_IX ON HCM.LOCATIONS (CITY ASC) ;

CREATE INDEX HCM.LOC_COUNTRY_IX ON HCM.LOCATIONS (COUNTRY_ID ASC);

CREATE UNIQUE INDEX HCM.LOC_ID_PK ON HCM.LOCATIONS (LOCATION_ID ASC);

CREATE INDEX HCM.LOC_STATE_PROVINCE_IX ON HCM.LOCATIONS (STATE_PROVINCE ASC);

CREATE UNIQUE INDEX HCM.REG_ID_PK ON HCM.REGIONS (REGION_ID ASC) ;

ALTER TABLE HCM.DEPARTMENTS
ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY 
(
  DEPARTMENT_ID 
)
USING INDEX HCM.DEPT_ID_PK
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY 
(
  EMPLOYEE_ID 
)
USING INDEX HCM.EMP_EMP_ID_PK
ENABLE;

ALTER TABLE HCM.JOBS
ADD CONSTRAINT JOB_ID_PK PRIMARY KEY 
(
  JOB_ID 
)
USING INDEX HCM.JOB_ID_PK
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY 
(
  EMPLOYEE_ID 
, START_DATE 
)
USING INDEX HCM.JHIST_EMP_ID_ST_DATE_PK
ENABLE;

ALTER TABLE HCM.LOCATIONS
ADD CONSTRAINT LOC_ID_PK PRIMARY KEY 
(
  LOCATION_ID 
)
USING INDEX HCM.LOC_ID_PK
ENABLE;

ALTER TABLE HCM.REGIONS
ADD CONSTRAINT REG_ID_PK PRIMARY KEY 
(
  REGION_ID 
)
USING INDEX HCM.REG_ID_PK
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_EMAIL_UK UNIQUE 
(
  EMAIL 
)
USING INDEX 
(
    CREATE UNIQUE INDEX HCM.EMP_EMAIL_UK ON HCM.EMPLOYEES (EMAIL ASC)
)
 ENABLE;

ALTER TABLE HCM.COUNTRIES
ADD CONSTRAINT COUNTR_REG_FK FOREIGN KEY
(
  REGION_ID 
)
REFERENCES HCM.REGIONS
(
  REGION_ID 
)
ENABLE;

ALTER TABLE HCM.DEPARTMENTS
ADD CONSTRAINT DEPT_LOC_FK FOREIGN KEY
(
  LOCATION_ID 
)
REFERENCES HCM.LOCATIONS
(
  LOCATION_ID 
)
ENABLE;

ALTER TABLE HCM.DEPARTMENTS
ADD CONSTRAINT DEPT_MGR_FK FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES HCM.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_DEPT_FK FOREIGN KEY
(
  DEPARTMENT_ID 
)
REFERENCES HCM.DEPARTMENTS
(
  DEPARTMENT_ID 
)
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_JOB_FK FOREIGN KEY
(
  JOB_ID 
)
REFERENCES HCM.JOBS
(
  JOB_ID 
)
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_MANAGER_FK FOREIGN KEY
(
  MANAGER_ID 
)
REFERENCES HCM.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_DEPT_FK FOREIGN KEY
(
  DEPARTMENT_ID 
)
REFERENCES HCM.DEPARTMENTS
(
  DEPARTMENT_ID 
)
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_EMP_FK FOREIGN KEY
(
  EMPLOYEE_ID 
)
REFERENCES HCM.EMPLOYEES
(
  EMPLOYEE_ID 
)
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_JOB_FK FOREIGN KEY
(
  JOB_ID 
)
REFERENCES HCM.JOBS
(
  JOB_ID 
)
ENABLE;

ALTER TABLE HCM.LOCATIONS
ADD CONSTRAINT LOC_C_ID_FK FOREIGN KEY
(
  COUNTRY_ID 
)
REFERENCES HCM.COUNTRIES
(
  COUNTRY_ID 
)
ENABLE;

ALTER TABLE HCM.COUNTRIES
ADD CONSTRAINT COUNTRY_ID_NN CHECK 
("COUNTRY_ID" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.DEPARTMENTS
ADD CONSTRAINT DEPT_NAME_NN CHECK 
("DEPARTMENT_NAME" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_EMAIL_NN CHECK 
("EMAIL" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_HIRE_DATE_NN CHECK 
("HIRE_DATE" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_JOB_NN CHECK 
("JOB_ID" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_LAST_NAME_NN CHECK 
("LAST_NAME" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.EMPLOYEES
ADD CONSTRAINT EMP_SALARY_MIN CHECK 
(salary > 0)
ENABLE;

ALTER TABLE HCM.JOBS
ADD CONSTRAINT JOB_TITLE_NN CHECK 
("JOB_TITLE" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_DATE_INTERVAL CHECK 
(end_date > start_date)
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_EMPLOYEE_NN CHECK 
("EMPLOYEE_ID" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_END_DATE_NN CHECK 
("END_DATE" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_JOB_NN CHECK 
("JOB_ID" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.JOB_HISTORY
ADD CONSTRAINT JHIST_START_DATE_NN CHECK 
("START_DATE" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.LOCATIONS
ADD CONSTRAINT LOC_CITY_NN CHECK 
("CITY" IS NOT NULL)
ENABLE;

ALTER TABLE HCM.REGIONS
ADD CONSTRAINT REGION_ID_NN CHECK 
("REGION_ID" IS NOT NULL)
ENABLE;