CREATE TABLE HCM.INCIDENTS 
(
  INCIDENT_ID NUMBER(6) NOT NULL 
, EMPLOYEE_ID NUMBER(6) NOT NULL 
, REQUEST_DATE TIMESTAMP NOT NULL 
, CATEGORY_NAME VARCHAR2(100)
, DESCRIPTION VARCHAR2(500) 
, CURRENT_STATUS VARCHAR2(20) NOT NULL 
, CONSTRAINT INCIDENT_PK PRIMARY KEY 
  (
    INCIDENT_ID 
  )
  ENABLE 
);

CREATE TABLE HCM.INCIDENT_ATTENTIONS
(
  INCIDENT_ATTENTION_ID NUMBER(6) NOT NULL 
, INCIDENT_ID NUMBER(6) NOT NULL 
, ATTENTION_DATE TIMESTAMP NOT NULL 
, ACTIONS VARCHAR2(500) 
, USERNAME VARCHAR2(50) NOT NULL 
, CONSTRAINT INCIDENT_ATTENTION_PK PRIMARY KEY 
  (
    INCIDENT_ATTENTION_ID 
  )
  ENABLE 
);


ALTER TABLE HCM.INCIDENT_ATTENTIONS
ADD CONSTRAINT INC_INC_ATT_FK FOREIGN KEY
(
  INCIDENT_ID 
)
REFERENCES HCM.INCIDENTS
(
  INCIDENT_ID 
)
ON DELETE CASCADE ENABLE;

CREATE SEQUENCE HCM.INCIDENTS_SEQ INCREMENT BY 1 MAXVALUE 999999 MINVALUE 1 NOCACHE;

