
package com.oracle.xmlns.caseservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.oracle.xmlns.caseservice.types.TCloseCaseInputMessage;
import com.oracle.xmlns.caseservice.types.TCloseCaseOutputMessage;
import com.oracle.xmlns.caseservice.types.TForceCloseCaseInputMessage;
import com.oracle.xmlns.caseservice.types.TForceCloseCaseOutputMessage;
import com.oracle.xmlns.caseservice.types.TMilestoneInputMessage;
import com.oracle.xmlns.caseservice.types.TMilestoneOutputMessage;
import com.oracle.xmlns.caseservice.types.TStartCaseInputMessage;
import com.oracle.xmlns.caseservice.types.TStartCaseOutputMessage;
import com.oracle.xmlns.caseservice.types.TSuspendResumeAbortCaseInputMessage;
import com.oracle.xmlns.caseservice.types.TSuspendResumeAbortCaseOutputMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "CaseServicePortType", targetNamespace = "http://xmlns.oracle.com/CaseService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
            com.oracle.xmlns.caseservice.types.ObjectFactory.class,
            oracle.bpm.casemgmt.metadata.caseinstance.model.ObjectFactory.class,
            oracle.bpm.casemgmt.metadata.common.model.ObjectFactory.class,
            oracle.bpm.casemgmt.metadata.extension.model.ObjectFactory.class
    })
public interface CaseServicePortType {


    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TStartCaseOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "startCase")
    @WebResult(name = "startCaseOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TStartCaseOutputMessage startCase(@WebParam(name = "startCaseInputMessage",
                                                       targetNamespace = "http://xmlns.oracle.com/CaseService/types",
                                                       partName = "payload")
                                             TStartCaseInputMessage payload) throws CaseServiceFaultMessage;

    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TMilestoneOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "attainMilestone")
    @WebResult(name = "attainMilestoneOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TMilestoneOutputMessage attainMilestone(@WebParam(name = "attainMilestoneInputMessage",
                                                             targetNamespace =
                                                             "http://xmlns.oracle.com/CaseService/types",
                                                             partName = "payload")
                                                   TMilestoneInputMessage payload) throws CaseServiceFaultMessage;

    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TMilestoneOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "revokeMilestone")
    @WebResult(name = "revokeMilestoneOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TMilestoneOutputMessage revokeMilestone(@WebParam(name = "revokeMilestoneInputMessage",
                                                             targetNamespace =
                                                             "http://xmlns.oracle.com/CaseService/types",
                                                             partName = "payload")
                                                   TMilestoneInputMessage payload) throws CaseServiceFaultMessage;

    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TSuspendResumeAbortCaseOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "abortCase")
    @WebResult(name = "abortCaseOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TSuspendResumeAbortCaseOutputMessage abortCase(@WebParam(name = "abortCaseInputMessage",
                                                                    targetNamespace =
                                                                    "http://xmlns.oracle.com/CaseService/types",
                                                                    partName = "payload")
                                                          TSuspendResumeAbortCaseInputMessage payload) throws CaseServiceFaultMessage;

    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TSuspendResumeAbortCaseOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "suspendCase")
    @WebResult(name = "suspendCaseOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TSuspendResumeAbortCaseOutputMessage suspendCase(@WebParam(name = "suspendCaseInputMessage",
                                                                      targetNamespace =
                                                                      "http://xmlns.oracle.com/CaseService/types",
                                                                      partName = "payload")
                                                            TSuspendResumeAbortCaseInputMessage payload) throws CaseServiceFaultMessage;

    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TSuspendResumeAbortCaseOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "resumeCase")
    @WebResult(name = "resumeCaseOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TSuspendResumeAbortCaseOutputMessage resumeCase(@WebParam(name = "resumeCaseInputMessage",
                                                                     targetNamespace =
                                                                     "http://xmlns.oracle.com/CaseService/types",
                                                                     partName = "payload")
                                                           TSuspendResumeAbortCaseInputMessage payload) throws CaseServiceFaultMessage;

    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TCloseCaseOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "closeCase")
    @WebResult(name = "closeCaseOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TCloseCaseOutputMessage closeCase(@WebParam(name = "closeCaseInputMessage",
                                                       targetNamespace = "http://xmlns.oracle.com/CaseService/types",
                                                       partName = "payload")
                                             TCloseCaseInputMessage payload) throws CaseServiceFaultMessage;

    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TSuspendResumeAbortCaseOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "reopenCase")
    @WebResult(name = "reopenCaseOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TSuspendResumeAbortCaseOutputMessage reopenCase(@WebParam(name = "reopenCaseInputMessage",
                                                                     targetNamespace =
                                                                     "http://xmlns.oracle.com/CaseService/types",
                                                                     partName = "payload")
                                                           TSuspendResumeAbortCaseInputMessage payload) throws CaseServiceFaultMessage;

    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.caseservice.types.TForceCloseCaseOutputMessage
     * @throws CaseServiceFaultMessage
     */
    @WebMethod(action = "forceCloseCase")
    @WebResult(name = "forceCloseCaseOutputMessage", targetNamespace = "http://xmlns.oracle.com/CaseService/types",
               partName = "payload")
    public TForceCloseCaseOutputMessage forceCloseCase(@WebParam(name = "forceCloseCaseInputMessage",
                                                                 targetNamespace =
                                                                 "http://xmlns.oracle.com/CaseService/types",
                                                                 partName = "payload")
                                                       TForceCloseCaseInputMessage payload) throws CaseServiceFaultMessage;

}
