
package com.oracle.xmlns.caseservice;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "IncidentManagementProcess.service", targetNamespace = "http://xmlns.oracle.com/CaseService",
                  wsdlLocation =
                  "http://ougn15-acm:7011/soa-infra/services/default/IncidentManagementProcess/IncidentManagementProcess.service?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FCaseService%7DIncidentManagementProcess.service")
public class IncidentManagementProcessService extends Service {

    private final static URL INCIDENTMANAGEMENTPROCESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException INCIDENTMANAGEMENTPROCESSSERVICE_EXCEPTION;
    private final static QName INCIDENTMANAGEMENTPROCESSSERVICE_QNAME =
        new QName("http://xmlns.oracle.com/CaseService", "IncidentManagementProcess.service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://ougn15-acm:7011/soa-infra/services/default/IncidentManagementProcess/IncidentManagementProcess.service?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FCaseService%7DIncidentManagementProcess.service");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INCIDENTMANAGEMENTPROCESSSERVICE_WSDL_LOCATION = url;
        INCIDENTMANAGEMENTPROCESSSERVICE_EXCEPTION = e;
    }

    public IncidentManagementProcessService() {
        super(__getWsdlLocation(), INCIDENTMANAGEMENTPROCESSSERVICE_QNAME);
    }

    public IncidentManagementProcessService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INCIDENTMANAGEMENTPROCESSSERVICE_QNAME, features);
    }

    public IncidentManagementProcessService(URL wsdlLocation) {
        super(wsdlLocation, INCIDENTMANAGEMENTPROCESSSERVICE_QNAME);
    }

    public IncidentManagementProcessService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INCIDENTMANAGEMENTPROCESSSERVICE_QNAME, features);
    }

    public IncidentManagementProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IncidentManagementProcessService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CaseServicePortType
     */
    @WebEndpoint(name = "CaseServicePort")
    public CaseServicePortType getCaseServicePort() {
        return super.getPort(new QName("http://xmlns.oracle.com/CaseService", "CaseServicePort"),
                             CaseServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaseServicePortType
     */
    @WebEndpoint(name = "CaseServicePort")
    public CaseServicePortType getCaseServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/CaseService", "CaseServicePort"),
                             CaseServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INCIDENTMANAGEMENTPROCESSSERVICE_EXCEPTION != null) {
            throw INCIDENTMANAGEMENTPROCESSSERVICE_EXCEPTION;
        }
        return INCIDENTMANAGEMENTPROCESSSERVICE_WSDL_LOCATION;
    }

}
